[deps]
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"

[sources]
LanguageServer = {rev = "e2032a58c51d4745768d3f5dd21594e4441e7876", url = "https://github.com/julia-vscode/LanguageServer.jl.git"}
