[deps]
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"

[sources]
LanguageServer = {rev = "66732ddb4c0fe85d2c5b30771e8c73a4dbdfd7c0", url = "https://github.com/julia-vscode/LanguageServer.jl.git"}
